services:
  web_app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/mydatabase
    ports:
      - "8000:7000"
    volumes:
      - ./src:/app

#контейнер базы данных
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

#контейнер UI субд
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.command
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


