"""foreing_keys

Revision ID: 0003
Revises: 0002
Create Date: 2025-06-18 21:28:26.084895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car', 'user', ['user_id'], ['id'])
    op.add_column('consumable', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consumable', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consumable', type_='foreignkey')
    op.drop_column('consumable', 'car_id')
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'user_id')
    # ### end Alembic commands ###
